Fix non-existing executables.
size: Print a warning when an executable does not exist.

      Warning: cubic executable not found.
      Warning: md5sum executable not found.
      Benchmark            size
      ---------            ----
      aha-mont64          27.47
      crc32               92.41
      cubic                0.00

speed: Fail gracefully with a nice error message instead of a python
       trace.

       Warning: cubic executable not found.
       Warning: md5sum executable not found.
       Benchmark           Speed
       ---------           -----
       ...
       ud                  10.59
       wikisort            21.80
       ERROR: Failed to compute speed benchmarks

Signed-off-by: Daniel Schultz <d.schultz@phytec.de>